---
title: "Model fitting in R"
output: html_document
---

Scratch notes from our in-class activities in Lecture 3. This covers the model-fitting paradigm in R.

```{r}
library(tidyverse)
```

Use the `iris` data to demonstrate. Split into training and test data:

```{r}
head(iris)
set.seed(100)
iris <- mutate(
	iris, 
	training = caTools::sample.split(Sepal.Width, SplitRatio=0.8))
#	   training = sample(1:2, replace=TRUE, prob=c(0.8, 0.2), size=nrow(iris)))
iris_train <- filter(iris, training)
iris_test <- filter(iris, !training)
#caret::createDataPartition()
```

Fit a LOESS model:

```{r}
fit <- loess(Sepal.Width ~ Petal.Width, data=iris_train)
```

Make predictions:

```{r}
yhat <- predict(fit, newdata=iris_test)
```

Calculate error:

```{r}
mean((yhat - iris_test$Sepal.Width)^2)
```

## `broom` package

```{r}
library(broom)
#tidy(fit)
#glance(fit)
augment(fit, newdata = iris_test)
```

With linear regression:

```{r}
fit2 <- lm(Sepal.Width ~ Petal.Width, data=iris_train)
#unclass(fit2)
#unclass(summary(fit2))

tidy(fit2)
augment(fit2)
glance(fit2)
```

