---
title: "BAIT 509 Lecture 2"
output: html_document
---

Let's explore the Default data set:

```{r}
library(ISLR)
library(tidyverse)
head(Default)
nrow(Default)
table(Default$default)
##Overall error:
333/10000
```

Plot all the data:

```{r, fig.width=6, fig.height=3}
ggplot(Default, 
	   aes(x=income, y=balance, colour=default)) +
	geom_point(alpha=0.2) +
	facet_wrap(~ student)
```

```{r}
pred <- ifelse(Default$balance > 1750, "Yes", "No")
correct <- sum(pred == Default$default)
1 - correct/10000
```

## Iris example

```{r}
p <- 15
ggplot(iris, aes(Petal.Width, Sepal.Width)) +
    geom_point(alpha = 0.2) +
    geom_smooth(method = "lm", formula = y ~ poly(x, p)) +
    theme_bw()
```

```{r}
set.seed(100)
train_id <- sample(nrow(iris), 100)
train <- iris[train_id, ]
test <- iris[-train_id, ]

mse <- numeric(0)
for (p in 1:15) {
	fit <- lm(Sepal.Width ~ poly(Petal.Width, p), train)
	error <- predict(fit, newdata=test) - test$Sepal.Width
	mse <- c(mse, mean(error^2))
}
mse
qplot(1:15, mse, geom=c("point", "line"))
```


